/* PELAGIA — the aquarium's facts: halls, the daily schedule, tickets,
   experiences, reviews and the gallery. Prices are in Singapore dollars.
   Times are the day's timetable; the pages work out what is next. */
window.PELAGIA = {
  hours: { open: '10:00', close: '19:00', lateClose: '22:00', lateDays: [5, 6], lastEntry: 60 },

  halls: [
    {
      slug: 'open-ocean', name: 'Open Ocean', tag: 'The 36-metre window',
      icon: 'wave',
      blurb: 'Seven and a half million litres behind a single 36-metre acrylic window, twelve metres tall. Two whale sharks, a reef manta, spotted eagle rays and a school of two thousand jacks pass every few minutes.',
      facts: ['7.5 million litres', '36 m × 12 m window, 700 mm acrylic', '2 whale sharks, 1 reef manta', 'Dive feed 13:00 daily'],
      img: 'img/hall-open-ocean.webp', img2560: 'img/hall-open-ocean-2560.webp',
      alt: 'A whale shark passing the Open Ocean window with jacks and rays behind it',
      video: 'video/loop-shark.mp4', poster: 'img/loop-shark-poster.webp',
    },
    {
      slug: 'jellies', name: 'The Jellies', tag: 'Seven species, twelve kreisels',
      icon: 'jelly',
      blurb: 'Moon jellies, sea nettles, upside-down jellies and blue blubbers in circular kreisel tanks lit from below. The darkest hall in the building, and the quietest.',
      facts: ['7 species', '12 kreisel tanks', 'Bred on site since 2021', 'Talk 12:00 daily'],
      img: 'img/hall-jellies.webp', img2560: 'img/hall-jellies-2560.webp',
      alt: 'Moon jellies drifting in blue light',
      video: 'video/loop-jellies.mp4', poster: 'img/loop-jellies-poster.webp',
    },
    {
      slug: 'reef', name: 'Reef Edge', tag: 'A living coral reef and the touch pool',
      icon: 'coral',
      blurb: 'A 400,000-litre reef grown from fragments over six years: clownfish, mandarins, a green turtle called Mabel, and Ray Bay, the shallow pool where you can put a hand in.',
      facts: ['400,000 litres', '2,300 corals, 140 fish species', 'Ray Bay touch pool', 'Dive feed 10:30 daily'],
      img: 'img/hall-reef.webp', img2560: 'img/hall-reef-2560.webp',
      alt: 'A green turtle over a coral reef with angelfish and butterflyfish',
    },
    {
      slug: 'seagrass', name: 'Seagrass & Mangrove', tag: 'The nursery',
      icon: 'grass',
      blurb: 'The shallow, green end of the Straits: a seagrass meadow with blind sharks and seahorses, and a mangrove tank with archerfish that spit at a target on the hour.',
      facts: ['Singapore Strait species', 'Archerfish target 11:15 & 14:15', 'Seahorse breeding room', 'Wheelchair-height windows'],
      img: 'img/hall-seagrass.webp', img2560: 'img/hall-seagrass-2560.webp',
      alt: 'A blind shark resting in a seagrass meadow',
    },
    {
      slug: 'penguins', name: 'Penguin Cove', tag: 'Little penguins, 16 °C',
      icon: 'penguin',
      blurb: 'Twenty-two little penguins from a breeding programme with Phillip Island, in a chilled cove with an underwater viewing bay. Feeds at 11:00 and 16:00; bring a jumper.',
      facts: ['22 little penguins', 'Kept at 16 °C', 'Underwater viewing bay', 'Feeds 11:00 & 16:00'],
      img: 'img/hall-penguins.webp', img2560: 'img/hall-penguins-2560.webp',
      alt: 'A little penguin on the rocks of Penguin Cove',
    },
  ],

  /* [time, title, hall slug, where, minutes, days] — days: 'daily' or 'late' (Fri & Sat evenings) */
  schedule: [
    ['10:30', 'Reef dive feed', 'reef', 'Reef Edge, lower window', 20, 'daily'],
    ['11:00', 'Penguin feed', 'penguins', 'Penguin Cove', 15, 'daily'],
    ['11:15', 'Archerfish target', 'seagrass', 'Mangrove tank', 10, 'daily'],
    ['11:30', 'Ray Bay feed', 'reef', 'Ray Bay touch pool', 25, 'daily'],
    ['12:00', 'Jellies talk', 'jellies', 'The Jellies, kreisel 7', 20, 'daily'],
    ['13:00', 'Open Ocean dive feed', 'open-ocean', 'The 36-metre window', 30, 'daily'],
    ['14:00', 'Behind the Glass tour', 'open-ocean', 'Meet at the top of the ramp', 60, 'daily'],
    ['14:15', 'Archerfish target', 'seagrass', 'Mangrove tank', 10, 'daily'],
    ['15:00', 'Ray Bay feed', 'reef', 'Ray Bay touch pool', 25, 'daily'],
    ['15:30', 'Shark Dive', 'open-ocean', 'Divers only, Sat & Sun', 45, 'daily'],
    ['16:00', 'Penguin feed', 'penguins', 'Penguin Cove', 15, 'daily'],
    ['17:00', 'Open Ocean talk', 'open-ocean', 'The 36-metre window', 20, 'daily'],
    ['19:30', 'Jellies after dark', 'jellies', 'The Jellies, with music', 40, 'late'],
    ['20:30', 'Night feed', 'open-ocean', 'The 36-metre window', 30, 'late'],
  ],

  tickets: {
    adult: 42, child: 30, senior: 32, family: 128,
    afterDark: 36, gate: 4,
    annual: { adult: 118, child: 78 },
    slots: ['10:00', '11:00', '12:00', '13:00', '14:00', '15:00', '16:00', '17:00'],
    lateSlots: ['19:00', '20:00'],
  },

  experiences: [
    {
      slug: 'shark-dive', name: 'Shark Dive', price: 280, unit: 'per diver',
      when: 'Saturdays & Sundays, 15:30', duration: '45 min in the water', ages: 'Certified divers, 15+', capacity: 4,
      img: 'img/card-shark-dive.webp', alt: 'Sand tiger sharks passing in the Open Ocean tank',
      blurb: 'Forty-five minutes in the Open Ocean tank with two aquarists, among the sand tigers, the whale sharks and the manta. Open Water certification required; all kit provided.',
      includes: ['All dive kit and a 5 mm suit', 'Briefing and a private changing room', 'Photographs from the window side', 'A second entry ticket for a friend to watch'],
      dates: ['2026-09-19', '2026-09-20', '2026-09-26', '2026-09-27', '2026-10-03', '2026-10-04'],
    },
    {
      slug: 'sleepover', name: 'Sleep with the Sharks', price: 180, unit: 'per person',
      when: 'One Saturday a month, 19:00 to 09:00', duration: 'Overnight', ages: '6 and over; under-16s with an adult', capacity: 40,
      img: 'img/card-sleepover.webp', alt: 'Two people at the Open Ocean window at night',
      blurb: 'A night on the carpet in front of the 36-metre window, with a torch-lit walk through the Jellies, supper, breakfast, and the dive feed before the doors open.',
      includes: ['Supper and breakfast', 'Sleeping mat and pillow (bring a bag)', 'The night feed and the morning dive feed', 'Next-day entry to the whole aquarium'],
      dates: ['2026-09-26', '2026-10-24', '2026-11-21', '2026-12-19'],
    },
    {
      slug: 'backstage', name: 'Behind the Glass', price: 68, unit: 'per person',
      when: 'Daily, 14:00', duration: '60 min', ages: '8 and over', capacity: 12,
      img: 'img/card-backstage.webp', alt: 'A visitor at the reef window as the fish gather',
      blurb: 'Up the ramp to the top of the Open Ocean tank, into the food kitchen and the coral nursery, then the quarantine room where every animal starts.',
      includes: ['The top of the Open Ocean tank', 'Coral nursery and quarantine', 'An aquarist for the full hour', 'Entry ticket included'],
      dates: ['daily'],
    },
    {
      slug: 'ray-feed', name: 'Ray Bay Feed', price: 28, unit: 'per person', addon: true,
      when: 'Daily, 11:30 & 15:00', duration: '25 min', ages: '5 and over', capacity: 10,
      img: 'img/card-ray-feed.webp', alt: 'Spotted eagle rays over the sand',
      blurb: 'Stand in the shallow end of Ray Bay with an aquarist and hand-feed the cownose and eagle rays as they come to the wall.',
      includes: ['Waders and a towel', 'A bucket of squid and an aquarist', 'Entry ticket not included — add it to a visit'],
      dates: ['daily'],
    },
  ],

  reviews: [
    ['Nadia Rahman', 'Visited with two children, August 2026', 'We went for the dive feed at one and stayed until the penguins at four. The window is bigger than the photographs make it look. The Ray Bay feed was the thing my six-year-old talked about for a week.'],
    ['Cheng Wei Lim', 'After Dark, September 2026', 'The Jellies with the lights down and the music on is the calmest place in Singapore on a Friday night. S$36 and no children under twelve — exactly what it says.'],
    ['Sophie Marchetti', 'Behind the Glass, July 2026', 'Standing at the top of the tank while the whale shark came up to look at us. The aquarist answered every question for an hour and then walked us to the coral nursery. Worth every dollar of the sixty-eight.'],
    ['Daniel Ong', 'Annual pass holder', 'We come most Sunday mornings for the reef feed at half ten and are home by lunch. The pass paid for itself in three visits and the queue-free entry is the real perk.'],
  ],

  /* [image, caption, hall slug, detail] */
  gallery: [
    ['img/hall-open-ocean.webp', 'The Open Ocean', 'open-ocean', 'A whale shark at the 36-metre window'],
    ['img/head-manta.webp', 'The Open Ocean', 'open-ocean', 'The reef manta, wingspan 3.4 m'],
    ['img/plate-sharks.webp', 'The Open Ocean', 'open-ocean', 'Sand tiger sharks before the 13:00 feed'],
    ['img/plate-rays.webp', 'Ray Bay', 'reef', 'Spotted eagle rays over the sand'],
    ['img/head-crowd.webp', 'The Open Ocean', 'open-ocean', 'The 13:00 dive feed from the gallery'],
    ['img/hall-jellies.webp', 'The Jellies', 'jellies', 'Moon jellies, kreisel 3'],
    ['img/plate-lilac.webp', 'The Jellies', 'jellies', 'Moon jellies under the lilac lights, after dark'],
    ['img/head-nettles.webp', 'The Jellies', 'jellies', 'Pacific sea nettles, kreisel 9'],
    ['img/plate-jelly-window.webp', 'The Jellies', 'jellies', 'The porthole at the end of the hall'],
    ['img/plate-single-jelly.webp', 'The Jellies', 'jellies', 'A moon jelly alone in kreisel 1'],
    ['img/hall-reef.webp', 'Reef Edge', 'reef', 'Mabel the green turtle over the reef'],
    ['img/plate-reef-tank.webp', 'Reef Edge', 'reef', 'The reef from the lower window'],
    ['img/plate-clownfish.webp', 'Reef Edge', 'reef', 'Clownfish in a magnificent anemone'],
    ['img/plate-mandarin.webp', 'Reef Edge', 'reef', 'Mandarinfish, the reef’s smallest residents'],
    ['img/plate-seadragon.webp', 'Seagrass & Mangrove', 'seagrass', 'A leafy seadragon in the seahorse room'],
    ['img/plate-turtle.webp', 'Reef Edge', 'reef', 'Mabel, from below'],
    ['img/hall-seagrass.webp', 'Seagrass & Mangrove', 'seagrass', 'A blind shark in the seagrass meadow'],
    ['img/plate-touch.webp', 'Reef Edge', 'reef', 'The reef window at opening time'],
    ['img/hall-penguins.webp', 'Penguin Cove', 'penguins', 'A little penguin at the 16:00 feed'],
    ['img/head-tunnel.webp', 'The Open Ocean', 'open-ocean', 'The tunnel under the Open Ocean tank'],
    ['img/plate-two-kids.webp', 'Reef Edge', 'reef', 'The reef window at child height'],
    ['img/plate-couple.webp', 'After Dark', 'open-ocean', 'The Open Ocean at 21:00 on a Friday'],
    ['img/hero-window.webp', 'The Open Ocean', 'open-ocean', 'The 36-metre window at 10:00'],
  ],
};
