"""UNFURL. — build the scroll-scrubbed frame sequence from the licensed master.

    python tools/film.py

Input : tools/raw/AdobeStock_737291599.mov  (Adobe Stock, 2160x3840, 25 fps, 29.28 s;
        gitignored — re-license from the free tier if missing, see IMAGE-CREDITS.md)
Output: film/xl/000..159.webp  2048x1152  landscape, wide or dense desktop screens
        film/l/000..159.webp   1440x810   landscape, desktop
        film/s/000..159.webp   720x1280   portrait, phones
        js/film-data.js         globalThis.FILM — frame count, sizes, per-frame mean colour

Every frame goes through one identical grade: the master is red-orange, and the
grade pulls it to amber (green lifted in proportion to red, blue trimmed, the
deepest reds eased toward brown) so the dark early frames read as wet leaf rather
than embers. The picture is cropped 72 px off the left (the teapot's glass wall
catches light there) and 24 px off the right. The landscape sets are a 16:9 band
of the portrait master whose centre follows focus: tools/focus.py measures where
the leaves are sharp in every frame and smooths that into a slow camera move
(tools/focus.json). Run focus.py first.
"""
import json, os, subprocess, sys, tempfile, shutil
import numpy as np
from PIL import Image

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'tools', 'raw', 'AdobeStock_737291599.mov')
N = 160
SIZES = {'xl': (2048, 1152, 60), 'l': (1440, 810, 62), 's': (720, 1280, 64)}
CROP_L, CROP_R = 72, 24


def probe_duration(path):
    out = subprocess.check_output(['ffprobe', '-v', 'error', '-show_entries', 'format=duration',
                                   '-of', 'csv=p=0', path]).decode().strip()
    return float(out)


def grade(a, k=0.9):
    """a: float32 HxWx3 in 0..1 -> amber, floor deepened onto the page ground."""
    r, g, b = a[..., 0], a[..., 1], a[..., 2]
    lum = 0.2126 * r + 0.7152 * g + 0.0722 * b
    out = np.stack([r * (1 - 0.04 * k), g + k * 0.16 * np.clip(r - g, 0, 1), b * (1 - 0.25 * k)], -1)
    sh = np.clip(1 - lum * 3, 0, 1)[..., None]
    brown = lum[..., None] * np.array([1.1, 0.95, 0.8], np.float32)
    out = out * (1 - 0.45 * k * sh) + brown * (0.45 * k * sh)
    out = np.clip((out - 0.035) / (1 - 0.035), 0, 1) ** 1.04
    return np.clip(out, 0, 1)


def main():
    if not os.path.exists(SRC):
        sys.exit('missing ' + SRC)
    dur = probe_duration(SRC)
    tmp = tempfile.mkdtemp(prefix='unfurl-')
    # evenly spaced timestamps, first and last frame included
    times = [i * (dur - 0.12) / (N - 1) for i in range(N)]
    for i, t in enumerate(times):
        subprocess.check_call(['ffmpeg', '-loglevel', 'error', '-y', '-ss', '%.3f' % t, '-i', SRC,
                               '-frames:v', '1', os.path.join(tmp, '%03d.png' % i)])
        if i % 20 == 0:
            print('decoded', i, '/', N)

    for k in SIZES:
        os.makedirs(os.path.join(ROOT, 'film', k), exist_ok=True)
    FOCUS = json.load(open(os.path.join(ROOT, 'tools', 'focus.json')))['centre']

    means = []
    for i in range(N):
        im = Image.open(os.path.join(tmp, '%03d.png' % i)).convert('RGB')
        W, H = im.size
        w = W - CROP_L - CROP_R
        a = grade(np.asarray(im.crop((CROP_L, 0, CROP_L + w, H))).astype(np.float32) / 255.0)
        g = Image.fromarray((a * 255 + 0.5).astype(np.uint8))
        # portrait, for phones: 9:16 about the centre
        ph = round(w * 16 / 9)
        port = g.crop((0, (H - ph) // 2, w, (H - ph) // 2 + ph))
        # landscape, for desktop: a 16:9 band that tilts down the frame over the steep
        lh = round(w * 9 / 16)
        c = FOCUS[i]
        top = int(round(min(max(c * H - lh / 2, 0), H - lh)))
        land = g.crop((0, top, w, top + lh))
        small = np.asarray(land.resize((64, 36), Image.BILINEAR)).astype(np.float32)
        means.append([int(round(v)) for v in small.reshape(-1, 3).mean(axis=0)])
        for k, (tw, th, q) in SIZES.items():
            src = port if th > tw else land
            src.resize((tw, th), Image.LANCZOS).save(
                os.path.join(ROOT, 'film', k, '%03d.webp' % i), quality=q, method=6)
        if i % 20 == 0:
            print('encoded', i)

    shutil.rmtree(tmp, ignore_errors=True)

    size = {k: sum(os.path.getsize(os.path.join(ROOT, 'film', k, f))
                   for f in os.listdir(os.path.join(ROOT, 'film', k))) for k in SIZES}
    data = {
        'n': N,
        'sourceSeconds': round(dur, 2),
        'sizes': {k: [v[0], v[1]] for k, v in SIZES.items()},
        'bytes': size,
        'mean': means,
    }
    js = ('/* generated by tools/film.py — do not edit by hand */\n'
          'globalThis.FILM = ' + json.dumps(data, separators=(',', ':')) + ';\n')
    with open(os.path.join(ROOT, 'js', 'film-data.js'), 'w', encoding='utf-8') as f:
        f.write(js)
    print('frames', N, 'bytes', size)


if __name__ == '__main__':
    main()
