/* YORIMICHI — the eight tours, their departures and prices.
   Prices are per person in Singapore dollars, twin-share, and include the
   return economy flight from Singapore. Departure dates are fixed; seats
   are the count still open on that date (0 = sold out, with a waitlist). */
window.YORI_TOURS = [
  {
    slug: 'golden-route',
    name: 'The Golden Route',
    short: 'Tokyo · Hakone · Kyoto · Osaka',
    tagline: 'The classic first Japan trip, done at a walking pace.',
    region: 'kanto-kansai',
    regionLabel: 'Kanto & Kansai',
    seasons: ['autumn', 'spring'],
    days: 10, nights: 9,
    priceFrom: 5980,
    single: 1180,
    physical: 'Moderate — 10 to 14 km on foot on city days',
    card: 'img/tour-golden-route-card.webp',
    wide: 'img/tour-golden-route-wide.webp',
    alt: 'A woman in a floral kimono walking up the lane below Yasaka Pagoda in Kyoto',
    gallery: [
      ['img/plate-shibuya.webp', 'Shibuya from above on night one'],
      ['img/plate-fushimi.webp', 'Fushimi Inari at 6:40 am, before the crowds'],
      ['img/plate-kyoto-lane.webp', 'Ninenzaka, Kyoto, the morning walk to Kiyomizu-dera'],
    ],
    highlights: [
      'Three nights in Shinjuku, three in central Kyoto, two in Osaka',
      'One night in a Hakone ryokan with a kaiseki dinner and open-air bath',
      'Fushimi Inari before the gates open to the crowds',
      'Shinkansen Tokyo–Odawara and Kyoto–Osaka, reserved seats',
      'A free day in Kyoto with your guide on call and a cycling option',
    ],
    itinerary: [
      ['Fly Singapore → Tokyo', 'Morning departure from Changi, arrive Haneda mid-afternoon. Private coach to the hotel in Shinjuku. Welcome dinner at an izakaya in Omoide Yokocho.'],
      ['Tokyo — old and new', 'Senso-ji and the Asakusa backstreets at opening time, a river bus down the Sumida, then Shibuya at dusk from the Sky deck.'],
      ['Tokyo — a free morning, then Yanaka', 'Sleep in or take the guide’s optional Tsukiji outer-market breakfast walk. Afternoon in Yanaka’s temple district and a sunset from Yanaka Ginza.'],
      ['Hakone by bullet train', 'Shinkansen to Odawara, the Hakone Tozan railway up the valley, a ropeway over Owakudani. Check in to a ryokan for kaiseki and the outdoor bath.'],
      ['Hakone → Kyoto', 'Lake Ashi in the morning (Fuji, weather permitting), then the Shinkansen west. Evening walk through Gion as the lanterns come on.'],
      ['Kyoto — east side', 'Fushimi Inari at 6:40 am, then Kiyomizu-dera, Ninenzaka and Sannenzaka, and a tea-ceremony lesson in a Higashiyama machiya.'],
      ['Kyoto — Arashiyama and a free afternoon', 'Bamboo grove before 8 am, Tenryu-ji garden, then the afternoon is yours: Nishiki market, a cycling loop, or nothing at all.'],
      ['Nara day trip', 'Todai-ji’s Great Buddha, the deer of Nara Park, a mochi-pounding stop in Nakatanidou, back to Kyoto by evening.'],
      ['Osaka', 'Local train to Osaka. Osaka Castle park, a Kuromon market lunch, and a Dotonbori street-food dinner with the guide.'],
      ['Fly Osaka → Singapore', 'Free morning. Coach to Kansai International, afternoon flight, arrive Changi in the evening.'],
    ],
    included: ['Return economy flights Singapore–Tokyo / Osaka–Singapore', '9 nights: 8 hotel, 1 ryokan', '9 breakfasts, 3 dinners', 'All rail incl. reserved Shinkansen seats', 'Full-time English/Mandarin-speaking tour leader', 'Temple, castle and museum entries listed'],
    excluded: ['Travel insurance (required — we can arrange it)', 'Lunches and unlisted dinners', 'Tips for local guides (optional, ~¥1,000 a day)', 'Single room supplement S$1,180'],
    departures: [
      ['2026-10-12', 5980, 2], ['2026-11-09', 6180, 0], ['2027-03-15', 5980, 8], ['2027-03-29', 6380, 6, 'Sakura'], ['2027-04-19', 5980, 10], ['2027-05-17', 5980, 12],
    ],
  },
  {
    slug: 'kyoto-autumn',
    name: 'Kyoto in Autumn',
    short: 'Kyoto · Nara · Arashiyama · Uji',
    tagline: 'Seven days in one city while the maples turn.',
    region: 'kansai',
    regionLabel: 'Kansai',
    seasons: ['autumn'],
    days: 7, nights: 6,
    priceFrom: 4860,
    single: 860,
    physical: 'Moderate — mostly on foot, some temple steps',
    card: 'img/tour-kyoto-autumn-card.webp',
    wide: 'img/tour-kyoto-autumn-wide.webp',
    alt: 'A woman in kimono under a red paper umbrella beneath scarlet maples in Kyoto',
    gallery: [
      ['img/plate-toji-pagoda.webp', 'To-ji pagoda reflected in the pond, late November'],
      ['img/plate-nara-deer.webp', 'Nara Park deer in the fallen maple leaves'],
      ['img/plate-torii-umbrella.webp', 'The Senbon Torii at Fushimi Inari'],
    ],
    highlights: [
      'Six nights in one machiya-district hotel — unpack once',
      'Evening illuminations at Eikan-do and Kodai-ji',
      'A morning at Nara Park while the deer are still hungry',
      'Uji matcha: a tea-grading session with a fourth-generation grower',
      'Guide-led early starts to beat the crowds at every headline temple',
    ],
    itinerary: [
      ['Fly Singapore → Osaka, coach to Kyoto', 'Arrive Kansai International in the afternoon. Coach to the hotel near Karasuma-Oike. Welcome dinner of obanzai home-style dishes.'],
      ['Higashiyama', 'Kiyomizu-dera at opening, the Ninenzaka lanes, Kodai-ji, then the evening illumination at Eikan-do.'],
      ['Arashiyama', 'Bamboo grove before 8 am, Tenryu-ji, the Togetsukyo bridge in colour, a boat on the Hozu river.'],
      ['Nara', 'Todai-ji and Kasuga Taisha’s lantern paths. Afternoon back in Kyoto for Tofuku-ji’s maple valley.'],
      ['Uji and a free evening', 'Byodo-in, a tea-grading session at a grower’s house, and the evening free.'],
      ['Fushimi and the north', 'Fushimi Inari at dawn, then Kinkaku-ji and Ryoan-ji’s stone garden. Farewell kaiseki dinner.'],
      ['Fly Osaka → Singapore', 'Free morning in Kyoto. Coach to the airport for the afternoon flight home.'],
    ],
    included: ['Return economy flights Singapore–Osaka', '6 nights in one central Kyoto hotel', '6 breakfasts, 2 dinners', 'All local rail and the Hozu river boat', 'Tour leader plus a Kyoto-licensed local guide', 'All temple entries and illuminations'],
    excluded: ['Travel insurance', 'Lunches and unlisted dinners', 'Single room supplement S$860'],
    departures: [
      ['2026-11-16', 4860, 3], ['2026-11-23', 4980, 0], ['2026-11-30', 4860, 5], ['2027-11-15', 4980, 12],
    ],
  },
  {
    slug: 'sakura',
    name: 'Sakura Season',
    short: 'Osaka · Kyoto · Nara · Tokyo',
    tagline: 'Nine days following the blossom front north.',
    region: 'kanto-kansai',
    regionLabel: 'Kansai & Kanto',
    seasons: ['spring'],
    days: 9, nights: 8,
    priceFrom: 6240,
    single: 1240,
    physical: 'Moderate — long park walks, some crowds',
    card: 'img/tour-sakura-card.webp',
    wide: 'img/tour-sakura-wide.webp',
    alt: 'Osaka Castle above cherry blossom at dusk',
    gallery: [
      ['img/tour-golden-route-wide.webp', 'Yasaka Pagoda and the Sannenzaka lanes in early April'],
      ['img/plate-nara-deer.webp', 'Nara Park in the morning'],
      ['img/plate-shibuya.webp', 'Tokyo on the last night'],
    ],
    highlights: [
      'Two hanami picnics with the guide — Osaka Castle park and Maruyama-koen',
      'The Philosopher’s Path at 7 am in full bloom',
      'Yozakura: cherry trees lit at night along the Meguro river',
      'Timed to the Japan Meteorological Agency forecast, with a flexible day in reserve',
      'Shinkansen Kyoto–Tokyo on the Fuji side of the train',
    ],
    itinerary: [
      ['Fly Singapore → Osaka', 'Arrive in the afternoon. Hotel in Namba, evening street-food walk in Dotonbori.'],
      ['Osaka', 'Osaka Castle park hanami picnic, Kuromon market, the Umeda Sky Building at sunset.'],
      ['Osaka → Kyoto', 'Train to Kyoto. Maruyama-koen’s weeping cherry, then Gion after dark.'],
      ['Kyoto — the Philosopher’s Path', 'Early walk from Ginkaku-ji to Nanzen-ji under the trees, Heian Shrine garden, a free afternoon.'],
      ['Nara', 'Day trip: Todai-ji, Nara Park, Mount Yoshino if the bloom is on (a flexible day).'],
      ['Kyoto → Tokyo', 'Shinkansen to Tokyo, seats booked on the Fuji side. Yozakura along the Meguro river.'],
      ['Tokyo', 'Chidorigafuchi moat by rowing boat, Ueno Park, Shinjuku Gyoen’s late varieties.'],
      ['Tokyo — free day', 'Yours. The guide has a list: Kamakura, TeamLab, the Ghibli Museum (pre-booked on request).'],
      ['Fly Tokyo → Singapore', 'Coach to Haneda for the midday flight, arriving Changi in the evening.'],
    ],
    included: ['Return economy flights Singapore–Osaka / Tokyo–Singapore', '8 nights in 4-star hotels', '8 breakfasts, 2 picnic lunches, 2 dinners', 'All rail incl. reserved Shinkansen seats', 'Tour leader throughout', 'Hanami picnic sets and all garden entries'],
    excluded: ['Travel insurance', 'Unlisted meals', 'Single room supplement S$1,240', 'Ghibli Museum tickets (S$18, on request)'],
    departures: [
      ['2027-03-26', 6240, 4], ['2027-04-02', 6440, 0], ['2027-04-06', 6240, 7],
    ],
  },
  {
    slug: 'snow-country',
    name: 'Snow Country',
    short: 'Nagano · Jigokudani · Takayama · Shirakawa-go · Kanazawa',
    tagline: 'Snow monkeys, thatched villages and the Japan Alps in deep winter.',
    region: 'chubu',
    regionLabel: 'Chubu',
    seasons: ['winter'],
    days: 8, nights: 7,
    priceFrom: 5420,
    single: 980,
    physical: 'Moderate — a 30-minute snow walk to the monkey park',
    card: 'img/tour-snow-country-card.webp',
    wide: 'img/tour-snow-country-wide.webp',
    alt: 'Japanese macaques bathing in a hot spring at Jigokudani as snow falls',
    gallery: [
      ['img/plate-shirakawa.webp', 'Shirakawa-go at blue hour during the winter light-up'],
      ['img/plate-private-onsen.webp', 'The private bath at the Takayama ryokan'],
      ['img/plate-travellers.webp', 'The group on the Kanazawa morning'],
    ],
    highlights: [
      'Jigokudani snow monkeys in their hot spring, before the tour buses',
      'A Shirakawa-go winter light-up night, with the viewpoint reserved',
      'Two ryokan nights with private baths — Takayama and Yamashiro Onsen',
      'Takayama morning market and a sake brewery tasting',
      'Kenroku-en in snow, with the yukitsuri rope cones up',
    ],
    itinerary: [
      ['Fly Singapore → Tokyo, Shinkansen to Nagano', 'Morning flight, then the Hokuriku Shinkansen straight from Tokyo station. Hotel by Zenko-ji.'],
      ['Jigokudani', 'Early drive to Yudanaka, the 30-minute forest walk to the monkey park, then Obuse’s chestnut town.'],
      ['Nagano → Matsumoto → Takayama', 'Matsumoto Castle, then the Alps by train and coach to Takayama. Ryokan night one.'],
      ['Takayama', 'Miyagawa morning market, the old merchant houses, a brewery tasting, Hida beef dinner.'],
      ['Shirakawa-go', 'Coach into the valley. A farmhouse lunch, the light-up from the Shiroyama viewpoint, night in a gassho-zukuri farmhouse.'],
      ['Kanazawa', 'Kenroku-en in the snow, Omicho market, Higashi Chaya. Ryokan at Yamashiro Onsen.'],
      ['Kanazawa → Tokyo', 'Hokuriku Shinkansen back to Tokyo, a free evening in Ginza.'],
      ['Fly Tokyo → Singapore', 'Coach to Narita, morning flight, home by evening.'],
    ],
    included: ['Return economy flights Singapore–Tokyo', '7 nights: 4 hotel, 2 ryokan, 1 farmhouse', '7 breakfasts, 4 dinners', 'All rail incl. Hokuriku Shinkansen', 'Snow-boot hire and crampons', 'Tour leader plus mountain guide'],
    excluded: ['Travel insurance (winter cover required)', 'Unlisted meals', 'Single room supplement S$980'],
    departures: [
      ['2027-01-18', 5420, 6, 'Light-up'], ['2027-02-08', 5420, 1, 'Light-up'], ['2027-02-22', 5280, 9],
    ],
  },
  {
    slug: 'onsen',
    name: 'Onsen & Ryokan Retreat',
    short: 'Sendai · Ginzan Onsen · Zao · Yamadera',
    tagline: 'Six slow days in Tohoku’s hot-spring towns.',
    region: 'tohoku',
    regionLabel: 'Tohoku',
    seasons: ['winter'],
    days: 6, nights: 5,
    priceFrom: 4380,
    single: 760,
    physical: 'Easy — one optional 1,000-step climb at Yamadera',
    card: 'img/tour-onsen-card.webp',
    wide: 'img/tour-onsen-wide.webp',
    alt: 'A traveller in a red coat on the snowy main street of Ginzan Onsen at night',
    gallery: [
      ['img/plate-private-onsen.webp', 'A room with its own spring-fed bath'],
      ['img/plate-shirakawa.webp', 'Snow country by night'],
      ['img/plate-travellers.webp', 'A small group, by day three'],
    ],
    highlights: [
      'Three ryokan, three different springs — sulphur, iron and alkaline',
      'Ginzan Onsen’s gas-lit main street after the day-trippers leave',
      'Zao’s snow monsters by ropeway, with a bath at the top',
      'Yamadera’s cliff temple, optional 1,015 steps',
      'A yukata-fitting and onsen-etiquette briefing on night one',
    ],
    itinerary: [
      ['Fly Singapore → Tokyo, Shinkansen to Sendai', 'Morning flight, then the Tohoku Shinkansen north. Hotel in Sendai; gyutan dinner.'],
      ['Sendai → Ginzan Onsen', 'Train and coach into the mountains. Afternoon at leisure in the ryokan; the street at night.'],
      ['Ginzan Onsen', 'A quiet day: the waterfall walk, a soba lesson, baths. Second night at the same inn.'],
      ['Zao Onsen', 'Ropeway to the snow monsters, then check in to a sulphur-spring ryokan.'],
      ['Yamadera → Sendai', 'The cliff temple (optional climb), then back to Sendai for a farewell dinner.'],
      ['Fly Tokyo → Singapore', 'Shinkansen to Tokyo, coach to Haneda, evening arrival at Changi.'],
    ],
    included: ['Return economy flights Singapore–Tokyo', '5 nights: 2 hotel, 3 ryokan', '5 breakfasts, 3 kaiseki dinners', 'All rail incl. Tohoku Shinkansen', 'Zao ropeway', 'Tour leader'],
    excluded: ['Travel insurance', 'Unlisted meals', 'Single room supplement S$760'],
    departures: [
      ['2026-12-04', 4380, 5], ['2027-01-15', 4480, 0], ['2027-02-05', 4480, 8], ['2027-02-19', 4380, 12],
    ],
  },
  {
    slug: 'tokyo-dark',
    name: 'Tokyo After Dark',
    short: 'Tokyo · Yokohama · Kamakura',
    tagline: 'Five nights in the city, with the evenings planned and the days free.',
    region: 'kanto',
    regionLabel: 'Kanto',
    seasons: ['autumn', 'winter', 'spring'],
    days: 5, nights: 4,
    priceFrom: 3290,
    single: 620,
    physical: 'Easy — city walking, late nights',
    card: 'img/tour-tokyo-dark-card.webp',
    wide: 'img/tour-tokyo-dark-wide.webp',
    alt: 'A traveller walking through a lantern-lit izakaya alley in Shinjuku',
    gallery: [
      ['img/plate-shibuya.webp', 'Shibuya from the sky deck'],
      ['img/plate-kyoto-lane.webp', 'The Kamakura day trip'],
      ['img/plate-travellers.webp', 'Yokohama Chinatown night'],
    ],
    highlights: [
      'Four evening walks: Golden Gai, Yanaka, Shimokitazawa, Yokohama Chinatown',
      'A reserved counter at a 12-seat sushi bar on night two',
      'Kamakura’s Great Buddha and the Enoden coastal train',
      'Days free with a guide-written list — or nothing',
      'Hotel in Shinjuku, one stop from everything',
    ],
    itinerary: [
      ['Fly Singapore → Tokyo', 'Afternoon arrival at Haneda, hotel in Shinjuku, and a first walk through Omoide Yokocho and Golden Gai.'],
      ['Free day; sushi counter', 'Optional Tsukiji breakfast walk. Evening: a reserved 12-seat sushi counter in Ginza.'],
      ['Kamakura', 'Enoden train along the coast, the Great Buddha, Hase-dera, back for a Shimokitazawa evening.'],
      ['Free day; Yokohama', 'Evening train to Yokohama: Chinatown, the Red Brick Warehouse, the harbour by night.'],
      ['Fly Tokyo → Singapore', 'Free morning. Coach to Haneda for the afternoon flight.'],
    ],
    included: ['Return economy flights Singapore–Tokyo', '4 nights in Shinjuku', '4 breakfasts, 1 sushi dinner', 'Suica card loaded with ¥3,000', 'Tour leader for all evenings and the Kamakura day'],
    excluded: ['Travel insurance', 'Unlisted meals', 'Single room supplement S$620'],
    departures: [
      ['2026-10-20', 3290, 4], ['2026-11-17', 3290, 7], ['2026-12-08', 3490, 2], ['2027-01-26', 3290, 12], ['2027-02-23', 3290, 12],
    ],
  },
  {
    slug: 'inland-sea',
    name: 'Hiroshima & the Inland Sea',
    short: 'Hiroshima · Miyajima · Onomichi · Kurashiki · Okayama',
    tagline: 'A week on the quiet side of Japan.',
    region: 'chugoku',
    regionLabel: 'Chugoku',
    seasons: ['autumn', 'spring'],
    days: 7, nights: 6,
    priceFrom: 4690,
    single: 840,
    physical: 'Moderate — an optional 35 km cycle on the Shimanami Kaido',
    card: 'img/tour-inland-sea-card.webp',
    wide: 'img/tour-inland-sea-wide.webp',
    alt: 'The floating torii gate of Itsukushima Shrine at Miyajima in evening light',
    gallery: [
      ['img/plate-travellers.webp', 'Onomichi’s temple walk'],
      ['img/plate-fushimi.webp', 'A Kyoto stop on the way home'],
      ['img/plate-kyoto-lane.webp', 'Kurashiki’s canal quarter'],
    ],
    highlights: [
      'A night on Miyajima after the last ferry, torii at high tide',
      'Hiroshima Peace Memorial with a museum-trained local guide',
      'The Shimanami Kaido cycle across the islands (or the bus)',
      'Kurashiki’s canal quarter and the Ohara Museum',
      'Okayama’s Koraku-en garden at opening',
    ],
    itinerary: [
      ['Fly Singapore → Osaka, Shinkansen to Hiroshima', 'Morning flight, Shinkansen west, hotel by the river.'],
      ['Hiroshima', 'Peace Memorial Park and Museum, Shukkei-en garden, okonomiyaki dinner.'],
      ['Miyajima', 'Ferry across, Itsukushima Shrine, Mount Misen by ropeway. Night in a ryokan on the island.'],
      ['Onomichi and the Shimanami Kaido', 'Train to Onomichi, the temple walk, then the cycle across the bridges (or the bus) to Setoda.'],
      ['Kurashiki', 'The Bikan canal quarter, the Ohara Museum, a denim-town detour.'],
      ['Okayama → Osaka', 'Koraku-en garden at opening, then the Shinkansen to Osaka for a farewell dinner.'],
      ['Fly Osaka → Singapore', 'Coach to Kansai International for the afternoon flight.'],
    ],
    included: ['Return economy flights Singapore–Osaka', '6 nights: 5 hotel, 1 ryokan', '6 breakfasts, 3 dinners', 'All rail and ferries, reserved Shinkansen seats', 'Bicycle hire on the Shimanami Kaido', 'Tour leader plus a Hiroshima local guide'],
    excluded: ['Travel insurance', 'Unlisted meals', 'Single room supplement S$840'],
    departures: [
      ['2026-11-02', 4690, 3], ['2027-03-14', 4690, 10], ['2027-05-10', 4590, 12],
    ],
  },
  {
    slug: 'fuji-lakes',
    name: 'Fuji & the Five Lakes',
    short: 'Kawaguchiko · Fujiyoshida · Hakone · Tokyo',
    tagline: 'Six days circling the mountain, with a ryokan on the lake.',
    region: 'kanto',
    regionLabel: 'Kanto & Chubu',
    seasons: ['autumn', 'spring'],
    days: 6, nights: 5,
    priceFrom: 3980,
    single: 720,
    physical: 'Easy to moderate — the 398 steps to Chureito Pagoda',
    card: 'img/tour-fuji-lakes-card.webp',
    wide: 'img/tour-fuji-lakes-wide.webp',
    alt: 'Chureito Pagoda with Mount Fuji behind it at dusk',
    gallery: [
      ['img/film-fuji-poster.webp', 'Fuji over Lake Kawaguchiko at sunrise'],
      ['img/plate-shibuya.webp', 'Tokyo, the last night'],
      ['img/plate-private-onsen.webp', 'The lakeside ryokan bath'],
    ],
    highlights: [
      'Two nights in a lakeside ryokan with Fuji from the bath',
      'Chureito Pagoda at sunrise — the photograph everyone wants, without the crowd',
      'Oshino Hakkai’s spring ponds and a hoto noodle lunch',
      'Hakone’s open-air museum and the Owakudani ropeway',
      'A clear-day guarantee: if Fuji hides all week, S$300 back',
    ],
    itinerary: [
      ['Fly Singapore → Tokyo, coach to Kawaguchiko', 'Morning flight, direct coach from Haneda to the lake. Ryokan check-in and dinner.'],
      ['Chureito and the northern shore', 'Sunrise at Chureito Pagoda, Oshino Hakkai, a hoto lunch, the Kawaguchiko ropeway.'],
      ['The Five Lakes', 'Lake Motosu (the ¥1,000-note view), Saiko’s Iyashi-no-Sato village, Lake Yamanaka at sunset.'],
      ['Hakone', 'Coach to Hakone: the open-air museum, Owakudani, Lake Ashi cruise. Hotel in Gora.'],
      ['Hakone → Tokyo', 'Romancecar to Shinjuku, a free afternoon, farewell dinner in Ebisu.'],
      ['Fly Tokyo → Singapore', 'Coach to Haneda for the afternoon flight.'],
    ],
    included: ['Return economy flights Singapore–Tokyo', '5 nights: 2 ryokan, 3 hotel', '5 breakfasts, 3 dinners', 'All coaches, ropeways and the Romancecar', 'Tour leader'],
    excluded: ['Travel insurance', 'Unlisted meals', 'Single room supplement S$720'],
    departures: [
      ['2026-10-26', 3980, 1], ['2026-11-16', 4180, 6, 'Autumn colour'], ['2027-04-12', 4180, 9, 'Sakura'], ['2027-04-26', 3980, 12],
    ],
  },
];

window.YORI_REVIEWS = [
  ['Priya Nair', 'The Golden Route, April 2026', 'Twelve of us, one guide who knew which side of the train to sit on and which temple to reach before the buses. The ryokan night in Hakone alone was worth the fare.'],
  ['Marcus Goh', 'Snow Country, February 2026', 'I have been to Japan six times and this was the first trip where I did not plan a single thing. The Shirakawa-go light-up viewpoint was reserved. We just walked up.'],
  ['Adeline & Wei Sheng Tan', 'Onsen & Ryokan Retreat, January 2026', 'Six days, three inns, no suitcases to drag through stations — they forward them ahead. Ginzan at night, after the day-trippers left, was the quietest place we have ever been.'],
  ['Hannah Lim', 'Tokyo After Dark, December 2025', 'Free days, planned evenings. The sushi counter on night two would have taken me a year to get into on my own.'],
];

window.YORI_GALLERY = [
  ['img/plate-fushimi.webp', 'Fushimi Inari Taisha, Kyoto', 'kansai', 'Senbon Torii, 6:40 am'],
  ['img/plate-shibuya.webp', 'Shibuya, Tokyo', 'kanto', 'From the Sky deck, night one'],
  ['img/tour-inland-sea-wide.webp', 'Itsukushima Shrine, Miyajima', 'chugoku', 'High tide, evening'],
  ['img/plate-shirakawa.webp', 'Shirakawa-go, Gifu', 'chubu', 'Winter light-up'],
  ['img/tour-fuji-lakes-wide.webp', 'Chureito Pagoda, Fujiyoshida', 'kanto', 'Dusk, November'],
  ['img/tour-golden-route-wide.webp', 'Yasaka Pagoda, Kyoto', 'kansai', 'Sannenzaka, spring'],
  ['img/tour-kyoto-autumn-wide.webp', 'Kyoto', 'kansai', 'Maples, late November'],
  ['img/tour-sakura-wide.webp', 'Osaka Castle', 'kansai', 'Hanami at dusk'],
  ['img/tour-snow-country-wide.webp', 'Jigokudani, Nagano', 'chubu', 'The snow monkeys’ bath'],
  ['img/tour-onsen-wide.webp', 'Ginzan Onsen, Yamagata', 'tohoku', 'Gas lamps, after nine'],
  ['img/tour-tokyo-dark-wide.webp', 'Shinjuku, Tokyo', 'kanto', 'Omoide Yokocho'],
  ['img/plate-torii-umbrella.webp', 'Fushimi Inari Taisha, Kyoto', 'kansai', 'The Senbon Torii'],
  ['img/plate-nara-deer.webp', 'Nara Park', 'kansai', 'Deer in the maples'],
  ['img/plate-toji-pagoda.webp', 'To-ji, Kyoto', 'kansai', 'The five-storey pagoda'],
  ['img/plate-private-onsen.webp', 'Takayama', 'chubu', 'A room with its own spring'],
  ['img/plate-kyoto-lane.webp', 'Ninenzaka, Kyoto', 'kansai', 'The morning walk'],
  ['img/plate-travellers.webp', 'Kanazawa', 'chubu', 'The group, day three'],
  ['img/plate-milkyway.webp', 'Night sky', 'chubu', 'From the ridge, 4 am'],
];
